package model.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Retrieval values from result sets.
 * Result set object is table of data representing database result set
 * which usually generated by executing statement that queries the database.
 * @param <T> entity type
 */
public interface Mapper<T> {

    /**
     * Extracts value form result set. The result set declares getter methods
     * for retrieving column values from row.
     * @param rs is table of data representing database result set
     * @return entity
     * @throws SQLException when column name does not exist
     */
    T extract(ResultSet rs) throws SQLException;

}
