package model.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.function.Function;

/**
 * Retrieval values from result sets
 * Result set object is table of data representing a database result set
 * which usually generated by executing a statement that
 * @param <T> entity type
 */
public interface Mapper<T> {

    /**
     *
     * @param rs
     * @return
     * @throws SQLException
     */
    T extract(ResultSet rs) throws SQLException;

}
